-- AlterTable
ALTER TABLE "Job" ADD COLUMN     "budgetHours" DOUBLE PRECISION NOT NULL DEFAULT 0;

-- AlterTable
ALTER TABLE "HrPolicy" ADD COLUMN     "maxHoursPerThreeWeeks" DOUBLE PRECISION NOT NULL DEFAULT 144,
ADD COLUMN     "maxOvertimeHoursPerDay" DOUBLE PRECISION NOT NULL DEFAULT 2;

