/**
 * Author a PostgreSQL migration from the current schema.
 *
 * The project keeps one schema file whose provider is swapped at build time —
 * SQLite for zero-install local development, PostgreSQL on the host. Migration
 * SQL is provider-specific, so migrations are written for PostgreSQL only, and
 * local development stays on `prisma db push` against its disposable database.
 *
 *   npm run db:migration -- add-cost-centres
 *
 * The difference is taken against a snapshot of the schema as it stood at the
 * last migration, kept beside the migrations. Prisma's own `--from-migrations`
 * would need a spare PostgreSQL server to replay them into; comparing two
 * datamodels needs no database at all, which means a migration can be written
 * and reviewed anywhere.
 *
 * Read the SQL before committing it. That review is the whole point: a push
 * decides for itself at 3am, a migration is something a person agreed to.
 */
import { execFileSync } from "node:child_process";
import { existsSync, mkdirSync, readFileSync, writeFileSync, readdirSync, copyFileSync } from "node:fs";
import path from "node:path";

const MIGRATIONS = "prisma/migrations";
const PG_SCHEMA = "prisma/.pg.prisma";
const SNAPSHOT = path.join(MIGRATIONS, ".snapshot.prisma");
const EMPTY = "prisma/.empty.prisma";

const name = (process.argv[2] || "").trim().replace(/[^a-zA-Z0-9-]+/g, "-").replace(/^-+|-+$/g, "");
if (!name) {
  console.error("\nName the migration:  npm run db:migration -- add-cost-centres\n");
  process.exit(1);
}

/** The schema as PostgreSQL sees it. The URL is never connected to. */
function pgSchema() {
  return readFileSync("prisma/schema.prisma", "utf8")
    .replace(/provider = "(?:sqlite|postgresql)"/, 'provider = "postgresql"')
    .replace(/url\s*=\s*env\("DATABASE_URL"\)/, 'url      = env("MIGRATION_DATABASE_URL")');
}

function prisma(args) {
  return execFileSync("npx", ["prisma", ...args], {
    encoding: "utf8",
    shell: process.platform === "win32",
    env: { ...process.env, MIGRATION_DATABASE_URL: "postgresql://user:pass@localhost:5432/db" },
  });
}

writeFileSync(PG_SCHEMA, pgSchema());
mkdirSync(MIGRATIONS, { recursive: true });

const lock = path.join(MIGRATIONS, "migration_lock.toml");
if (!existsSync(lock)) {
  writeFileSync(lock, '# Please do not edit this file manually\nprovider = "postgresql"\n');
}

// The starting point: the previous snapshot, or an empty schema for the first.
let from;
if (existsSync(SNAPSHOT)) {
  from = ["--from-schema-datamodel", SNAPSHOT];
} else {
  writeFileSync(
    EMPTY,
    'datasource db {\n  provider = "postgresql"\n  url      = env("MIGRATION_DATABASE_URL")\n}\n'
  );
  from = ["--from-schema-datamodel", EMPTY];
}

const sql = prisma(["migrate", "diff", ...from, "--to-schema-datamodel", PG_SCHEMA, "--script"]);
const meaningful = sql.split("\n").filter((l) => l.trim() && !l.trim().startsWith("--")).join("\n").trim();

if (!meaningful) {
  console.log("No schema changes since the last migration — nothing to write.");
  process.exit(0);
}

const stamp = new Date().toISOString().replace(/\D/g, "").slice(0, 14);
const dir = path.join(MIGRATIONS, `${stamp}_${name}`);
mkdirSync(dir, { recursive: true });
writeFileSync(path.join(dir, "migration.sql"), sql);

// The snapshot moves forward, so the next migration diffs against this one.
copyFileSync(PG_SCHEMA, SNAPSHOT);

// The four shapes that can fail or lose data on a live table. A unique index
// is included because that is exactly what stopped the server starting twice:
// Prisma refuses to add one with `db push` in case the column holds duplicates.
const destructive = /DROP TABLE|DROP COLUMN|SET NOT NULL|CREATE UNIQUE INDEX|ADD CONSTRAINT[^;]*UNIQUE/i.test(sql);

console.log(`\nWrote ${dir}/migration.sql`);
console.log(`Existing migrations: ${readdirSync(MIGRATIONS).filter((d) => /^\d+_/.test(d)).length}\n`);
console.log(sql.split("\n").filter((l) => l.trim()).slice(0, 40).join("\n"));

if (destructive) {
  console.log(
    "\n  ⚠  This migration drops something, makes a column required, or adds a\n" +
      "     unique constraint. Any of those can fail or lose data on a live\n" +
      "     database. Read it line by line before it goes anywhere near the client."
  );
}
console.log("\nReview the SQL, then commit it with the schema change.");
