-- AlterTable
ALTER TABLE "Employee" ADD COLUMN     "lastWorkingDay" TIMESTAMP(3);

-- AlterTable
ALTER TABLE "Payslip" ADD COLUMN     "contractAllowances" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "contractBasic" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "daysInPeriod" INTEGER NOT NULL DEFAULT 30,
ADD COLUMN     "daysPaid" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "deductionNote" TEXT,
ADD COLUMN     "otHours" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "otPremiumHours" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "otherDeductions" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "overtime" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "partMonthReason" TEXT,
ADD COLUMN     "unpaidDays" DOUBLE PRECISION NOT NULL DEFAULT 0;

-- AlterTable
ALTER TABLE "Attendance" ADD COLUMN     "otHours" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "otPremiumHours" DOUBLE PRECISION NOT NULL DEFAULT 0;

